swagger: '2.0'
info:
  version: '0.0.1'
  title: RBKmoney Payment Resource API
  description: >

    Платформа предоставляет возможность токенизации исходных данных пользовательских платёжных ресурсов.
    Используя RBKmoney Payment Resource API вы можете для своего платёжного ресурса получить уникальный токен,
    который может быть использован для переводов.


  termsOfService: http://rbk.money/
  contact:
    name: RBKmoney support team
    email: support@rbk.money
    url: https://rbk.money
host: api.rbk.money
basePath: /payres/v0
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >
      Для аутентификации вызовов мы используем [JWT](https://jwt.io).
      Cоответствующий ключ передается в заголовке.

      ```shell
       Authorization: Bearer {TOKENIZATION|PRIVATE_JWT}
      ```

security:
  - bearer: []

responses:

  NotFound:
    description: Искомая сущность не найдена

  BadRequest:
    description: Недопустимые для операции входные данные
    schema:
      $ref: '#/definitions/BadRequest'

parameters:

  requestID:
    name: X-Request-ID
    in: header
    description: Уникальный идентификатор запроса к системе
    required: true
    type: string
    maxLength: 32
    minLength: 1

tags:

  - name: Payment Resources
    x-displayName: Платёжные ресурсы
    description: ""
